language: node_js
node_js:
  - 'node'
env:
  global:
  - 'SFTP_USER=[user]'
  - 'SFTP_PASSWORD=[password]'
  - 'SFTP_KEY=[base64-encoded-rsa-key]'
after_success:
- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
#- curl -T index.html
#       --key /tmp/sftp_rsa
#       sftp://${SFTP_USER}:${SFTP_PASSWORD}@120.79.211.49/www/index.html
- sftp