language: node_js
node_js:
  - 'node'
after_success:
  - echo "${rsa}" | base64 --decode >/tmp/rsa
  - cat /tmp/rsa
#- curl -T index.html
#       --key /tmp/rsa
#       sftp://${user}:${password}@120.79.211.49/www/index.html