language: node_js
node_js:
  - 'node'
env:
  global:
  - 'SFTP_USER=[user]'
  - 'SFTP_PASSWORD=[password]'
after_success:
- curl -T index.html
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@120.79.211.49/www/index.html