language: node_js
node_js:
  - "node"
addons:
  packages:
    - curl 7.29.0
cache:
  directories:
    - node_modules
after_success:
  - echo "${rsa}" | base64 --decode >/tmp/rsa
  - tar -czvf /tmp/dist.tar dist
  - curl --version
  - curl -T /tmp/dist.tar
         -k
         --key /tmp/rsa
         sftp://mysftp@120.79.211.49/www/