language: node_js
node_js:
  - 'node'
after_success:
- echo "${password}"
- echo "${base64-encoded-rsa-key}" | base64 --decode >/tmp/sftp_rsa
#- curl -T index.html
#       --key /tmp/sftp_rsa
#       sftp://${SFTP_USER}:${SFTP_PASSWORD}@120.79.211.49/www/index.html